### PR TITLE
Added log options to app

### PR DESCRIPTION
**Pull request by CreepyPvP**

### CODE REVIEW

**Comment by CreepyPvP** [comment]
Not that great looking. If required ill improve the appearance

**Comment by CreepyPvP** [comment]
Forgot tail input validation. Pr is WIP

**Comment by 0xle0ne** [comment]
Can you upload a screenshot to see how it look please @CreepyPvP ?

**Comment by CreepyPvP** [comment]
screenshot

**Comment by 0xle0ne** [comment]
thx!

**Pull request merged**
